/**
 * This code was generated by Builder.io.
 */
import React from "react";
import CourseLevel from "./CourseLevel";
import HeaderC from "./HeaderC";
import Header from "../../../components/header/Header";
import Footer from "../../../components/footer/CorporateClients/Footer";


const courseLevels = [
  {
    title: "Beginner Level",
    description:
      "To provide high-quality Vietnamese language education that not only teaches the language but also immerses students in the rich culture and traditions of Vietnam.",
    target: "Know basic Vietnamese",
    time: "24 hours",
    money: "300USD",
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/ad5370759f473ee0dba396ab4d5c9c71280ce8ad51ae00439cc0ba684bee3550?apiKey=e34b0bbc442149bfa463a424862e236a&",
    imageAlt: "Beginner level course illustration",
  },
  {
    title: "Intermediate Level",
    description:
      "To provide high-quality Vietnamese language education that not only teaches the language but also immerses students in the rich culture and traditions of Vietnam.",
    target: "Know basic Vietnamese",
    time: "24 hours",
    money: "300USD",
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/6ff88efeff49c689978534da0d3df2335e463ebcbe5ad41be0b7c517caa87342?apiKey=e34b0bbc442149bfa463a424862e236a&",
    imageAlt: "Intermediate level course illustration",
  },
];

const CourseLearning: React.FC = () => {
  return (
    <div className="flex flex-col">
      <Header />
      <HeaderC />
      <section className="flex flex-col pb-20">
        <div className="flex flex-col px-px py-16 w-full max-md:max-w-full">
          <div className="flex flex-col">
            {courseLevels.map((course, index) => (
              <CourseLevel
                key={index}
                {...course}
                isReversed={index % 2 !== 0}
              />
            ))}
          </div>
        </div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/71584985d5aaf99f18868e5eea7dd4cfa8b2f79d5079356d49cf9b839d2e16d4?apiKey=e34b0bbc442149bfa463a424862e236a&"
          alt=""
          className="object-contain self-end -mt-28 mr-10 w-5 aspect-[0.59] max-md:mr-2.5"
        />
      </section>
      <Footer />
    </div>
  );
};

export default CourseLearning;
