/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Header: React.FC = () => {
  return (
    <header className="flex relative flex-col px-11 pt-16 pb-8 w-full bg-orange-500 max-md:px-5 max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/e4c37f2c6c1bfb41daffad753e79972e57fd6dd544fafac990005773e336ef2c?apiKey=e34b0bbc442149bfa463a424862e236a&"
        alt=""
        className="object-contain absolute top-0 left-1/2 opacity-40 z-0 max-w-full -translate-x-2/4 aspect-[5.35] translate-y-[0%] w-full h-full"
      />
      <nav className="z-0 text-xl font-light text-white max-md:max-w-full">
        <a href="/">Home</a>/ COURSE LEARNING
      </nav>
      <div className="flex z-0 flex-col items-center self-end mt-2.5 max-w-full text-center w-[1358px]">
        <div className="flex flex-col max-w-full w-[1292px]">
          <h1 className="text-5xl leading-none text-white font-[250] max-md:max-w-full max-md:text-4xl">
            COURSE LEARNING
          </h1>
          <p className="mt-6 text-xl font-light text-white max-md:max-w-full">
            People passionate about language and culture
          </p>
        </div>
      </div>
      <button
        aria-label="Scroll down"
        className="flex z-0 gap-2.5 items-center self-end p-2.5 mt-2.5 bg-white rounded-3xl h-[50px] min-h-[50px] w-[50px]"
      >
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/b11e300f11913cd1648df9fe474cdbb993049757bb4198dd722bddb26c904f81?apiKey=e34b0bbc442149bfa463a424862e236a&"
          alt="Scroll down icon"
          className="object-contain aspect-square w-[30px]"
        />
      </button>
    </header>
  );
};

export default Header;
