/**
 * This code was generated by Builder.io.
 */
import React from "react";

const DashedBorder: React.FC = () => (
  <div className="shrink-0 max-w-full h-0.5 border-2 border-orange-500 border-dashed w-[1440px]" />
);

export default DashedBorder;
