/**
 * This code was generated by Builder.io.
 */
import React from "react";
import TeachingMethods from "./TeachingMethods";
import CulturalImmersion from "./CulturalImmersion";

const LanguageLearningPage: React.FC = () => (
  <main className="flex flex-col">
    <TeachingMethods />
    <CulturalImmersion />
  </main>
);

export default LanguageLearningPage;
