/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface SectionTitleProps {
  children: React.ReactNode;
}

const SectionTitle: React.FC<SectionTitleProps> = ({ children }) => (
  <h2 className="text-7xl leading-loose font-bold text-center text-orange-500 max-md:max-w-full max-md:text-4xl">
    {children}
  </h2>
);

export default SectionTitle;
