/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Button from "../../../components/button/Button";

const HeroSection: React.FC = () => {
  return (
    <section style={{height:`${window.innerHeight - 70}px`}} className={`flex flex-col justify-center items-center self-center w-full max-md:mt-10 max-md:max-w-full animate-fadeIn animate-once animate-ease-linear`}>
      <h1 className=" font-bold text-8xl text-center text-orange-500 leading-[118px] max-md:max-w-full max-md:text-4xl max-md:leading-[55px]">
        Master Vietnamese <br /> with ICLS
      </h1>
      <div className="flex flex-wrap gap-2 items-center self-center mt-8 text-2xl font-semibold text-black max-md:max-w-full">
        <Button label="Register now" primary  />
        <Button label="Contact Us" secondary link="contact"/>
      </div>
    </section>
  );
};

export default HeroSection;
