/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ButtonProps {
  children: React.ReactNode;
  className?: string;
}

const Button: React.FC<ButtonProps> = ({ children, className = "" }) => (
  <button
    className={`gap-2.5 self-center p-2.5 mt-8 max-w-full text-2xl font-semibold bg-orange-500 shadow-[4px_4px_0px_rgba(1,101,47,1)] w-[244px] ${className} transform transition-transform duration-300 hover:scale-105`}
  >
    {children}
  </button>
);

export default Button;
