/**
 * This code was generated by Builder.io.
 */
import React from "react";

import InstructorCard from "./InstructorCard";

interface Instructor {
    name: string;
    experience: string;
    imageSrc: string;
}
import { useEffect, useRef } from "react";

const instructors: Instructor[] = [
    {
        name: "Ms. Lan",
        experience: "5 years teaching Vietnamese",
        imageSrc:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/91c114f25928b9eb559870f3d74815abb4187463be1fdd31f406b7f4fedad609?apiKey=e34b0bbc442149bfa463a424862e236a&",
    },
    {
        name: "Ms. Lan",
        experience: "5 years teaching Vietnamese",
        imageSrc:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/91c114f25928b9eb559870f3d74815abb4187463be1fdd31f406b7f4fedad609?apiKey=e34b0bbc442149bfa463a424862e236a&",
    },
    {
        name: "Ms. Lan",
        experience: "5 years teaching Vietnamese",
        imageSrc:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/91c114f25928b9eb559870f3d74815abb4187463be1fdd31f406b7f4fedad609?apiKey=e34b0bbc442149bfa463a424862e236a&",
    },
    {
        name: "Ms. Lan",
        experience: "5 years teaching Vietnamese",
        imageSrc:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/91c114f25928b9eb559870f3d74815abb4187463be1fdd31f406b7f4fedad609?apiKey=e34b0bbc442149bfa463a424862e236a&",
    },
];

const ExperiencedInstructors: React.FC = () => {
    const sectionRef = useRef<HTMLElement>(null);

    //animation
    useEffect(() => {
        const observer = new IntersectionObserver(
            (entries) => {
                entries.forEach((entry) => {
                    if (entry.isIntersecting) {
                        entry.target.classList.add('animate-fadeIn');
                    }
                });
            },
            { threshold: 0.1 }
        );

        if (sectionRef.current) {
            observer.observe(sectionRef.current);
        }

        return () => {
            if (sectionRef.current) {
                observer.unobserve(sectionRef.current);
            }
        };
    }, []);
    console.log("render");
    return (
        <section className="pb-5 pt-5 lg:pb-5 lg:pt-20 dark:bg-dark">
            <section ref={sectionRef} className="container mx-auto">
                <div className="-mx-4 flex flex-wrap">
                    <div className="w-full px-4">
                        <div className="mx-auto mb-[60px] max-w-[510px] text-center">
                            <span className="mb-2 text-orange-400 block text-lg font-semibold">
                                Experienced Instructors
                            </span>
                            <h2 className="mb-3 text-3xl font-bold leading-[1.2] text-dark sm:text-4xl md:text-[40px] dark:text-white">
                                Our Awesome Team
                            </h2>
                            <p className="text-base text-body-color dark:text-dark-6">
                                Our instructors are native Vietnamese speakers
                                with extensive experience in teaching Vietnamese
                                as a foreign language.
                            </p>
                        </div>
                    </div>
                </div>
                <div className="-mx-4 flex flex-wrap">
                    {instructors.map((instructor, i) => (
                        <InstructorCard
                            key={i}
                            name={instructor.name}
                            experience={instructor.experience}
                            imageSrc={instructor.imageSrc}
                        />
                    ))}
                </div>
            </section>
        </section>
    );
};

export default ExperiencedInstructors;
