/**
 * This code was generated by Builder.io.
 */
import React from "react";
import HeaderAU from "./HeaderAU";
import Statistics from "./Statistics";
import MainContent from "./MainContent";
import Mission from "./Mission";
import Header from "../../components/header/Header";
import Footer from "../../components/footer/CorporateClients/Footer";

const AboutUs: React.FC = () => {
    return (
        <div className="flex flex-col bg-white w-screen">
            <Header />
            <HeaderAU />
            <section className="flex flex-col px-px py-16 w-full max-md:max-w-full">
                <h2 className="mt-8 text-5xl leading-loose text-center text-orange-500 font-[250] max-md:max-w-full max-md:text-4xl">
                    ESTABLISING OVER 10 YEARS
                </h2>
                <Statistics />
                <MainContent />
            </section>
            <Mission />
            <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/71584985d5aaf99f18868e5eea7dd4cfa8b2f79d5079356d49cf9b839d2e16d4?apiKey=e34b0bbc442149bfa463a424862e236a&"
                alt=""
                className="object-contain self-end -mt-28 mr-10 w-5 aspect-[0.59] max-md:mr-2.5"
            />
            <Footer />
        </div>
    );
};

export default AboutUs;
