/**
 * This code was generated by Builder.io.
 */
import React from "react";

const MainContent: React.FC = () => {
  return (
    <div className="flex flex-row gap-10 justify-center items-center mt-8 w-full text-black max-md:max-w-full">
      <div className="flex flex-col self-stretch my-auto min-w-[240px] w-[602px] max-md:max-w-full">
        <p className="text-3xl font-light leading-10 text-center max-md:max-w-full">
          Learn Vietnamese through our immersive and interactive teaching
          approach that blends traditional learning with modern techniques.
        </p>
        <button className="gap-2.5 self-center p-2.5 mt-8 max-w-full text-2xl font-semibold bg-orange-500 shadow-[4px_4px_0px_rgba(1,101,47,1)] w-[244px]">
          Register now
        </button>
      </div>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/7732b851616292889d1b3b9ed542a8fd38e8f4248995622ddb3b42b37d0ca795?apiKey=e34b0bbc442149bfa463a424862e236a&"
        alt="Vietnamese language learning illustration"
        className="object-contain self-stretch my-auto aspect-[1.41] min-w-[240px] w-[700px] max-md:flex max-md:max-w-full max-sm:hidden"
      />
    </div>
  );
};

export default MainContent;
