/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Mission: React.FC = () => {
  return (
    <section className="flex z-10 flex-col justify-center px-11 py-16 text-3xl font-light leading-10 text-center text-white bg-green-800 max-md:px-5 max-md:max-w-full">
      <div className="flex flex-col items-center max-w-full w-[1358px]">
        <p className="max-w-full w-[1292px] max-md:max-w-full">
          ICLS specializes in teaching Vietnamese language and culture to
          students from all around the world. We take pride in having
          successfully trained thousands of students and partnered with multiple
          organizations and businesses for the past three decades.
        </p>
      </div>
    </section>
  );
};

export default Mission;
