/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface StatisticProps {
  text: string;
}

const Statistic: React.FC<StatisticProps> = ({ text }) => (
  <div className="relative gap-2.5 self-stretch px-11 py-4 my-auto text-xl font-light text-black border border-amber-500 border-solid min-w-[240px] w-[325px] max-md:px-5">
    {text}
  </div>
);

const Statistics: React.FC = () => {
  const stats = [
    "60+ professionally trained teachers",
    "50000 students from 50+ countries",
    "100 corporate partners",
  ];

  return (
    <section className="flex flex-row gap-5 items-center self-center py-10 mt-8 -mr-1 text-center max-md:flex max-md:max-w-full max-sm:hidden">
      {stats.map((stat, index) => (
        <Statistic key={index} text={stat} />
      ))}
    </section>
  );
};

export default Statistics;
