/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ServiceCardProps {
    title: string;
    imageSrc: string;
}

const ServiceCard: React.FC<ServiceCardProps> = ({ title, imageSrc }) => {
    return (
        <div className="w-full px-4 md:w-1/2 lg:w-1/3 transform transition-transform duration-300 hover:scale-105">
            <div className="group mb-9 rounded-[20px] bg-white p-10 shadow-2 hover:shadow-lg md:px-7 xl:px-10 dark:bg-dark-2">
                <div className="mb-8 flex h-[70px] w-[70px] items-center justify-center rounded-2xl bg-primary bg-transparent">
                    <img src={imageSrc} alt="" className=" w-[100px] h-[100px]"/>
                </div>
                <h4 className="mb-[14px] text-2xl font-semibold text-dark dark:text-white">
                    {title}
                </h4>
                <p className=" group-hover:text-orange-3    00 text-body-color dark:text-dark-6">
                    We dejoy working with discerning clients, people for whom
                    qualuty, service, integrity & aesthetics.
                </p>
            </div>
        </div>
    );
};

export default ServiceCard;
