/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ServiceCard from "./ServiceCard";
import { useEffect, useRef } from "react";
interface ServiceCardProps {
    title: string;
    imageSrc: string;
}

const services: ServiceCardProps[] = [
    {
        title: "Corporation training",
        imageSrc:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/e921afacabc9371cc9d9b46908d13008631b84648e6d7ed808675d2a624df8c1?apiKey=e34b0bbc442149bfa463a424862e236a&",
    },
    {
        title: "Corporation training",
        imageSrc:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/e921afacabc9371cc9d9b46908d13008631b84648e6d7ed808675d2a624df8c1?apiKey=e34b0bbc442149bfa463a424862e236a&",
    },
    {
        title: "Corporation training",
        imageSrc:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/e921afacabc9371cc9d9b46908d13008631b84648e6d7ed808675d2a624df8c1?apiKey=e34b0bbc442149bfa463a424862e236a&",
    },
];
const Service: React.FC = () => {
    const sectionRef = useRef<HTMLElement>(null);
    //animation
    useEffect(() => {
        const observer = new IntersectionObserver(
            (entries) => {
                entries.forEach((entry) => {
                    if (entry.isIntersecting) {
                        entry.target.classList.add("animate-fadeIn");
                    }
                });
            },
            { threshold: 0.1 }
        );

        if (sectionRef.current) {
            observer.observe(sectionRef.current);
        }

        return () => {
            if (sectionRef.current) {
                observer.unobserve(sectionRef.current);
            }
        };
    }, []);
    return (
        <section ref={sectionRef} className="pb-5 pt-5 lg:pb-5 lg:pt-5 dark:bg-dark">
            <div className="container mx-auto">
                <div className="-mx-4 flex flex-wrap">
                    <div className="w-full px-4">
                        <div className="mx-auto mb-12 max-w-[510px] text-center lg:mb-20">
                            <span className="mb-2 block text-orange-400 text-lg font-semibold">
                                Our Services
                            </span>
                            <h2 className="mb-3 text-3xl font-bold leading-[1.2] text-dark sm:text-4xl md:text-[40px] dark:text-white">
                                What We Offer
                            </h2>
                            <p className="text-base text-body-color dark:text-dark-6">
                                There are many variations of passages of Lorem
                                Ipsum available but the majority have suffered
                                alteration in some form.
                            </p>
                        </div>
                    </div>
                </div>
                <div className="-mx-4 flex flex-wrap">
                    {services.map((service, i) => (
                        <ServiceCard
                            key={i}
                            title={service.title}
                            imageSrc={service.imageSrc}
                        />
                    ))}
                </div>
            </div>
        </section>
    );
};

export default Service;
