/**
 * This code was generated by Builder.io.
 */
import React from "react";
import JobListing from "./JobListing";
import HeaderC from "./HeaderC";
import Header from "../../components/header/Header";
import Footer from "../../components/footer/CorporateClients/Footer";

interface CareerOpportunitiesProps {}

const CareerOpportunities: React.FC<CareerOpportunitiesProps> = () => {
    const [activeCategory, setActiveCategory] = React.useState(0);
    const jobCategories = [
        { name: "All jobs", id: 0, key : "All" },
        { name: "Marketing", id: 1, key: "Marketing" },
        { name: "Human Resources", id: 2, key: "Human Resources" },
        { name: "Teaching assistants", id: 3, key: "Teaching assistants" },
    ];

    const jobListings = [
        {
            title: "Marketing",
            salary: "Negotiable salary",
            location: "Ho Chi Minh City",
            type: "Full time",
        },
        {
            title: "Human Resources",
            salary: "Negotiable salary",
            location: "Ho Chi Minh City",
            type: "Full time",
        },
        {
            title: "Teaching assistants",
            salary: "Negotiable salary",
            location: "Ho Chi Minh City",
            type: "Full time",
        },
        {
            title: "Human Resources",
            salary: "Negotiable salary",
            location: "Ho Chi Minh City",
            type: "Full time",
        },
    ];

    const handleCategoryClick = (id: number) => {
        setActiveCategory(id);
    };
    console.log(activeCategory);
    return (
        <div className="flex flex-col">
            <Header />
            <HeaderC />
            <div className="flex flex-col font-light text-black p-5">
                <h1 className="flex-1 self-center w-full text-5xl text-center text-orange-500 font-[250] leading-[118px] max-w-[1142px] min-h-[89px] max-md:max-w-full max-md:text-4xl max-md:leading-[110px]">
                    Career Opportunities
                </h1>
                <div className="flex flex-wrap gap-4 items-center mt-8 w-full text-xl text-center max-w-[1325px] max-md:max-w-full">
                    {jobCategories.map((category, index) => (
                        <div
                            className={` cursor-pointer gap-2.5 self-stretch p-2.5 my-auto rounded border border-black border-solid ${
                                activeCategory === index ? "bg-orange-500" : ""
                            }`}
                            onClick={() => handleCategoryClick(category.id)}
                        >
                            {category.name}
                        </div>
                    ))}
                </div>
                <div className="flex flex-col mt-9 w-full max-md:max-w-full">
                    {jobListings
                        .filter(
                            (job) =>
                                jobCategories[activeCategory].key === "All" ||
                                job.title === jobCategories[activeCategory].key
                        )
                        .map((job, index) => (
                            <JobListing
                                key={index}
                                title={job.title}
                                salary={job.salary}
                                location={job.location}
                                type={job.type}
                            />
                        ))}
                </div>
            </div>
            <Footer />
        </div>
    );
};

export default CareerOpportunities;
