/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface JobCategoryProps {
  key: number;
  name: string;
  isActive: boolean;
  handleCategoryClick: (id: number) => void;
}

const JobCategory: React.FC<JobCategoryProps> = ({key, name, isActive, handleCategoryClick}) => {
  console.log("JobCategoryProps", {key, name, isActive, handleCategoryClick})
  return (
    <div
      className={`gap-2.5 self-stretch p-2.5 my-auto rounded border border-black border-solid ${
        isActive ? "bg-orange-500" : ""
      }`}
      onClick={() => handleCategoryClick(key)}
    >
      {name}
    </div>
  );
};

export default JobCategory;
